apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-inntektsmelding-generator
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://flex-inntektsmelding-generator.dev.nav.no"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: ENVIRONMENT
      value: "q1"
    - name: OPPRETT_INNTEKTSMELDING_ROOT
      value: "https://flex-inntektsmelding-mock-proxy.dev.nav.no/api/v1/mock/inntektsmeldinger"
    - name: SLETT_INNTEKTSMELDING_ROOT
      value: "https://flex-inntektsmelding-mock-proxy.dev.nav.no/api/v1/mock/inntektsmeldinger"
